# Generated by Django 5.0.4 on 2025-03-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=220, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de puyblicacion')),
                ('Autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor')),
            ],
        ),
    ]
